apiVersion: v2
name: traction
description: The Traction service allows organizations to verify, hold, and issue verifiable credentials.
type: application
version: 0.0.5
appVersion: 0.2.12
home: "https://github.com/bcgov/traction"
sources: ["https://github.com/bcgov/traction"]
maintainers:
  - email: tools@usingtechnolo.gy
    name: usingtechnology
    url: https://github.com/usingtechnology
  - email: jason.syrotuck@nttdata.com
    name: Jsyro
    url: https://github.com/Jsyro
  - email: emiliano.sune@quartech.com
    name: esune
    url: https://github.com/esune
dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami/
    condition: persistence.deployPostgres
